export const PostsType = {
  ADD_POST: 'ADD_POST',
  MODIFY_POST: 'MODIFY_POST',
  FETCH_POSTS: 'FETCH_POSTS',
};

export const CategoriesType = {
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  ADD_CATEGORY: 'ADD_CATEGORY',
};

export const UsersType = {
  FETCH_USERS: 'FETCH_USERS',
  FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  CREATE_USER: 'CREATE_USER',
  FETCH_CURRENT_USER_POST: 'FETCH_CURRENT_USER_POST',
  DELETE_POST: 'DELETE_POST',
  CLEAR_ERROR: 'CLEAR_ERROR',
};
